name: Docker Image CI

on:
  push:
    paths:
      - './web'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io
        docker build ./container --tag sanoopsadique/securemail-linker:latest
        docker push docker.io/sanoopsadique/securemail-linker:latest
